# Generated by Django 2.1.3 on 2018-12-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
